### ISSUE TITLE
SteamCMD made a change to require force_install_dir to be before logon

### ISSUE THREAD

**Issue by asymptotic1** [ich777/docker-steamcmd-server#16]
+force_install_dir /<dir>/<gamedir>  has to be before +login now

**Comment by asymptotic1** [comment]
#17  proposed fix here

**Comment by ich777** [comment]
@asymptotic1 this doesn't make a difference from my testing and is also not necessary or better speaking doesn't affect the function from the container.

This is still the way to issue this command from the Steam Pipe documentation.

Do you go any issues with the container?

**Comment by asymptotic1** [comment]
@ich777 yeah, logs say STEAMCMD needs the force dir cmand to be before you login.    Looks like they made the change in the last week or so.

Following thread has the issue. 

https://githubmemory.com/repo/wolveix/satisfactory-server/activity?page=2

**Comment by asymptotic1** [comment]
`-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
[33;1mPlease use force_install_dir before logon!
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
[33;1mPlease use force_install_dir before logon!`

from logs.

**Comment by ich777** [comment]
@asymptotic1 yes, but the game is downloading or not?

I know this message and also the threads from Satisfactory and Conan Exiles for example, but they wont harm the function and the download process.

What game won't install for you? I need to know which game you are having troubles with so that I can test it on my own and see what it does.

I've tried various games (CS:Source, Valheim, Satisfactory, 7DtD,...) and they all work fine even with that warning.

Do you use the container on unRAID or another host?

**Comment by ich777** [comment]
As said in PR #17 I will merge this in my private Git repo and I will update the other branches too but this will take some time...
