### ISSUE TITLE
add optional support for metamod, amxmodx and fast download

### ISSUE THREAD

**Issue by realies** [ich777/docker-steamcmd-server#26]

**Comment by ich777** [comment]
@realies everything is supported by the container already…

**Comment by realies** [comment]
@ich777, how do you initialise it?

**Comment by ich777** [comment]
@realies just install Source MOD/Meta MOD or whatever you want like usual, of course be sure to stop the container first, make sure that you've downloaded the files for Linux and then start the container again.

**Comment by realies** [comment]
@ich777, I see. I meant to add these popular mods as an optional parameter, I managed to get things going by patching the game files with the latest https://github.com/AMXX-pl/BasePack and https://github.com/dreamstalker/rehlds over them.

**Comment by ich777** [comment]
@realies this is always a really hard decision to make if a mod should be integrated or not because this introduces additional complexity to the container and can ultimately break the container if the developers change anything how the plugins/mods are working. I've seen this a lot on Terraria for example (tModloader) and I've now deprecated this container because they change so much that I really can't keep up to keep the Docker working.

My main thought with this containers is that modding is always up to the user, I know it would be more convenient to have a single option but supporting those kind of things is a whole different story.

Supporting something that you don't actively use is a real pain sometimes, I think you get my point.

**Comment by realies** [comment]
Fair enough, I might fork the image and add the plugins after game file downloading completes. Are there any good hooks for this?

**Comment by ich777** [comment]
@realies sure thing, do whatever you want. It‘s OpenSource… :)

What do you mean with hooks? Do you mean how to install it?
You can take a look at my other repositories for example at the Valheim branch in this repo where I pull in the `start-server.sh` some mods if enabled.

**Comment by ich777** [comment]
I‘ll close this for now, if you need anything or anything isn‘t working feel free to open this issue again or create a new one.
