### ISSUE TITLE
wine can't resolve dns names

### ISSUE THREAD

**Issue by iccicci** [ich777/docker-steamcmd-server#28]
Simply awesome!

The only problem I'm experiencing is that wine seems not able to resolve dns names: the container is clearly able to do that... but I'm trying to load a V Rising server mod which need to resolve dns names but it logs "Could not resolve host" (I tested through wget inside the container and it works).

Any idea?
Thank you

**Comment by ich777** [comment]
Hi, what mod are you trying to install, usually I can't support modding since that's a but too much for me (don't know how every game is working because now I got really much games to support) but I'll try my best to help here.
From what I know most of the times V-Rising itself causes issues here but I really don't know how mods on V-Rising are working.
Also WINE should be able to resolve addresses just fine because other game servers rely on just that (Conan Exiles for example) and they also work just fine.
Why does a mod need to resolve a address btw...? 😆 
Which mod are you trying to run?

Cheers,
Christoph

**Comment by iccicci** [comment]
It's a mod I'm writing (is not published yet) and it needs to connect to an external server for its own purposes.

dns resolution is performed by the mod using .net API; it could be that only .net way to resolve names is affected by the problem...

**Comment by ich777** [comment]
Oh okay...

Does it work when you run the gameserver/mod on Windows? I really can't imagine that WINE is the issue here.
I'm not really familiar with .net but if you search for example `dotnet dns doesnt work` on Google you get a few results.

**Comment by iccicci** [comment]
I'll give it a try, thank you!
