### ISSUE TITLE
Game Request - Stormworks

### ISSUE THREAD

**Issue by blackwellj** [ich777/docker-steamcmd-server#38]
Could I request a new game be supported? I am wanting to host a server for stormworks

Here is the relevent infomation

App ID for SteamCMD is 1247090

Login can be anonymous

Default ports are UDP 25564 - 25566

Server binary name is server64.exe

There is also this guide for setting up servers

https://stormworks.fandom.com/wiki/Wiki/Guides/Dedicated_Server

Please let me know if you need any more infomation!

**Comment by ich777** [comment]
@blackwellj lucky for you that I've got the game already in my library.

The container is now done, if you are on Unraid you have to wait for a few hours so that it appears in the CA App, if not, there is already a new branch available called `stormworks`.

Hope that helps.

If you nee anything else feel free to open up a new issue, I'll close this issue. :)

**Comment by blackwellj** [comment]
Wow, Thats service!! thanks very much!!

**Comment by ich777** [comment]
@blackwellj just to be sure… you know that the server needs good single core performance and that it can cause lots of CPU usage even when empty…?
