### ISSUE TITLE
Server name

### ISSUE THREAD

**Issue by blackwellj** [ich777/docker-steamcmd-server#39]
Thankyou so much for getting this working! I’m now running this on a Ubuntu VM on some decent hardware. I’ve noticed on both normal docker and unraid that the game name is not being transmitted to steam? Is this somthing you’ve found on any other containers? If so do you know a fix? 

Thanks
James

**Comment by ich777** [comment]
Can you be a bit more precise please, about what game are we talking about (there are more than a few hand full of branches in this repository).
For a few game servers you have to pass a command line parameter over so that the correct name from the dedicated server is displayed in Steam.

But I'm not sure if this information will even help you since I don't know the exact game or if you mean something else.

Cheers,
Christoph

**Comment by blackwellj** [comment]
Sorry, it’s for stormworks
James Blackwell

On 3 Sep 2023, at 08:01, Christoph Hummer ***@***.***> wrote:

﻿

Can you be a bit more precise please, about what game are we talking about (there are more than a few hand full of branches in this repository).
For a few game servers you have to pass a command line parameter over so that the correct name from the dedicated server is displayed in Steam.

But I'm not sure if this information will even help you since I don't know the exact game or if you mean something else.

Cheers,
Christoph

**Comment by ich777** [comment]
I think you have to ask that on the forums/community support threads from Stormworks since it seems it's not related to the container because in game the server shows up with the specified name.
From a quick search I can't find much information about that but you can try to pass over `-name="YOURSERVERNAME"` in the `GAME_PARAMS` variable, but I'm assuming that won't make much difference.

Sorry but this seems like a game specific question since my container is like if you run it on bare metal with the installation and start from the server automated.
Since I can't find much information about that I can't help... :/

**Comment by ich777** [comment]
@blackwellj do you already made a post on the community forums from Stormworks? Can this be closed?

**Comment by blackwellj** [comment]
I haven’t but yes this can be closed
James Blackwell

On 6 Sep 2023, at 08:49, Christoph Hummer ***@***.***> wrote:

﻿

@blackwellj<https://github.com/blackwellj> do you already made a post on the community forums from Stormworks? Can this be closed?

**Comment by ich777** [comment]
@blackwellj sorry that I can't help here but I don't think that the Stormworks dedicated server is meant to connect through the Steam server browser (but I could be wrong about that).

Feel free to open up another issue if you are experiencing further issues and please also let me know about your findings.
