### ISSUE TITLE
Question about your Dockerfile for TheForestDedicatedServer

### ISSUE THREAD

**Issue by jammsen** [ich777/docker-steamcmd-server#8]
Hey @ich777 how are you?

I've created a similar docker-based container for the-forest, did you run into problems with content just disappearing too? 
I too got this down the line while i was still playing it too, but i never found a fix for it. I would love it if we could collab.

Here is a post of a user reporting it:
https://github.com/jammsen/docker-the-forest-dedicated-server/issues/10

**Comment by ich777** [comment]
No, never experienced something dissapearing...
I've played for about 6 months on my server and I know a lot of people that are using it without a problem.

I looked at your Dockerfile and how you run it but you have a completely different approach than me.

**Comment by jammsen** [comment]
@ich777 Yeah im using a process manager ontop to enable live updates in a nutshell concept.
Can you help me out by answering a few questions to your reslotuin:
Do you think it might a wine problem?
Do you think our Wine-Versions are that far from each other?
Why did you choose to use the key download version instead of the debain package version?

Basically:
https://github.com/ich777/docker-winehq-baseimage/blob/master/Dockerfile
vs 
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/Dockerfile#L16

I only see we install from different sources, maybe even different wine versions.

**Comment by ich777** [comment]
@jammsen 
> enable live updates in a nutshell concept.

I also do that in my Valheim container but without a process manager.
> Do you think it might a wine problem?

It may be possible, have you set the `WINEPREFIX` path and if yes where?
> Do you think our Wine-Versions are that far from each other?

I don't know what you are using but from my last buid log the WINE version in the container is: `Get:25 https://dl.winehq.org/wine-builds/debian buster/main amd64 wine-stable-amd64 amd64 5.0.2~buster [69.1 MB]`
> Why did you choose to use the key download version instead of the debain package version?

Because I prefer to run WINE in the most recent version because some newer games run better with newer version, for example Conan Exiles won't even run with a version that is before 5.x
I think the version that is in the stable Debian Buster repo is 4.0 or something like that...

You can try to switch to my baseimage if you want to for testing reasons, but I never experienced something disappear in the game even after a container update or multiple restarts.

Hoffe ich konnte dir helfen.
Schöne Grüße!

**Comment by ich777** [comment]
Will close this for now...

**Comment by jammsen** [comment]
> It may be possible, have you set the WINEPREFIX path and if yes where?

No i didnt, i only did WINEARCH and DISPLAY - See here: https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L49 - Can you explain whats that for?

> I don't know what you are using but from my last buid log the WINE version in the container is: Get:25  https://dl.winehq.org/wine-builds/debian buster/main amd64 wine-stable-amd64 amd64 5.0.2~buster [69.1 MB]

Mine looks like to be way older
`root@aaf39fce7933:/# wine --version
wine-4.0 (Debian 4.0-2)`

> You can try to switch to my baseimage if you want to for testing reasons, but I never experienced something disappear in the game even after a container update or multiple restarts.

I will try that, nice idea, thanks.

> Hoffe ich konnte dir helfen. Schöne Grüße! & Will close this for now...

Yeah go ahead, its not really a container/image problem on your side, i just didnt know how to get in contact with you otherwhise :X

You could, thank you so much
Konntest du vielen Dank
(Not sure what language you prefer ... :D )

**Comment by ich777** [comment]
The WINEPREFIX is basically the path where all Windows files are stored also files that eventually TheForest uses and WINE uses this path more or less as native Windows Filesystem with the C drive,..

I'm a little bit harder to reach but I'm always around in the Unraid forums. ;)

**Comment by jammsen** [comment]
@ich777 
Thanks for the info - Also i wrote you a dm in the unraid forums, i think there is a problem with Wine and Keys in that image of yours, regarding libfaudio0
